In [1]:
import numpy as np
import pandas as pd
pima = pd.read_csv("diabetes.csv")

In [2]:
pima.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
pima.shape

(768, 9)

In [4]:
pima.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [5]:
pima.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
pima["BloodPressure"] = pima["BloodPressure"].replace(0,np.NAN)

In [7]:
pima["Insulin"] = pima["Insulin"].replace(0,np.NAN)

In [8]:
pima["BMI"] = pima["BMI"].replace(0,np.NAN)

In [9]:
pima["Age"] = pima["Age"].replace(0,np.NAN)

In [10]:
pima.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148           72.0             35      NaN  33.6   
1            1       85           66.0             29      NaN  26.6   
2            8      183           64.0              0      NaN  23.3   
3            1       89           66.0             23     94.0  28.1   
4            0      137           40.0             35    168.0  43.1   
5            5      116           74.0              0      NaN  25.6   
6            3       78           50.0             32     88.0  31.0   
7           10      115            NaN              0      NaN  35.3   
8            2      197           70.0             45    543.0  30.5   
9            8      125           96.0              0      NaN   NaN   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

In [11]:
pima.isnull().sum()

Pregnancies                   0
Glucose                       0
BloodPressure                35
SkinThickness                 0
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [12]:
pima = pima.fillna({'BloodPressure':pima.BloodPressure.mean()})

In [13]:
pima = pima.fillna({'BMI':pima.BMI.mean()})

In [14]:
pima = pima.fillna({'Insulin':pima.Insulin.mean()})

In [15]:
pima = pima.fillna({'Age':pima.Age.mean()})

In [16]:
pima.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin        BMI  \
0            6      148      72.000000             35  155.548223  33.600000   
1            1       85      66.000000             29  155.548223  26.600000   
2            8      183      64.000000              0  155.548223  23.300000   
3            1       89      66.000000             23   94.000000  28.100000   
4            0      137      40.000000             35  168.000000  43.100000   
5            5      116      74.000000              0  155.548223  25.600000   
6            3       78      50.000000             32   88.000000  31.000000   
7           10      115      72.405184              0  155.548223  35.300000   
8            2      197      70.000000             45  543.000000  30.500000   
9            8      125      96.000000              0  155.548223  32.457464   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

In [17]:
feature=['BloodPressure','Insulin','BMI','Age']

In [18]:
X=pima[feature] #selccted features that falls under feature
Y=pima.Outcome  #index name (output)


In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=1,test_size=0.02)

In [20]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(X_train,Y_train)

C:\Users\KIIT\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
y_pred=log_reg.predict(X_test)

In [22]:
y_pred


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score
print (100*accuracy_score(Y_test,y_pred))

93.75


In [24]:
from sklearn.metrics import confusion_matrix

In [25]:
c_m=confusion_matrix(Y_test,y_pred)
c_m

array([[13,  0],
       [ 1,  2]], dtype=int64)

In [26]:
np.where(y_pred!=Y_test)  #index of wrong predicted data

(array([15], dtype=int64),)

In [27]:
y_pred[15]

0

In [28]:
# evaluation of the given data on the basis of predicted model

In [29]:
a=int(input("the bloodpressure : "))
b=int(input("the insulin level : "))
c=int(input("the BMI : "))
d=int(input("the age : "))

the bloodpressure : 98
the insulin level : 97
the BMI : 61
the age : 27


In [30]:
d1 = {'bloodpressure': [a], 'insulin level': [b], 'BMI': [c], 'age': [d]}

In [31]:

df=pd.DataFrame(data=d1)

In [32]:
df

bloodpressure  insulin level  BMI  age
0             98             97   61   27

In [33]:
prediction = log_reg.predict(df)

In [34]:
prediction  

#if array[0]  = the user does not have diabetes
#if array[1]  = the user has diabetes

array([1], dtype=int64)

In [35]:
import bs4
import requests
import re

In [36]:
url='https://www.mayoclinic.org/diseases-conditions/type-2-diabetes/in-depth/diabetes-prevention/art-20047639'    #url
data=requests.get(url)                    # getting that url
soup=bs4.BeautifulSoup(data.text,'html.parser')    #converting that url text to html so that we can read it
print(soup.prettify())                     # to show the complete data

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   403 - Forbidden: Access is denied.
  </title>
  <style type="text/css">
   <!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
  </style>
 </head>
 <body>
  <div id="header">
   <h1>
    Server Error
   </h1>
  </div>
  <div id="content">
 

In [37]:
soup

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<title>403 - Forbidden: Access is denied.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
<div class="content-container"><fieldset>

In [38]:
for i in soup.find_all('a'):
    i=i.get('href')
    #if i[0:3] =="/wa":    
    print('https://duckduckgo.com/'+i)    

In [39]:
import requests
import bs4
res=requests.get('https://www.mayoclinic.org/diseases-conditions/type-2-diabetes/in-depth/diabetes-prevention/art-20047639')
soup=bs4.BeautifulSoup(res.text,'lxml')
for i in soup.select('body'):
    print(i.text)



Server Error


403 - Forbidden: Access is denied.
You do not have permission to view this directory or page using the credentials that you supplied.



